---
- name: "Create Application Directory"
  file:
    path: ~/app
    state: directory


- name: "Add Application Source"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/app

- name: "Start Application"
  shell: |
    cd ~/app
    pm2 stop default
    pm2 start npm -- start
- name: "Check Application"
  shell: |
    pm2 status
    printenv
  register: server_setup
  changed_when: false

# - name: "Show Application Logs"
#   shell: |
#     pm2 logs
#   register: server_setup
#   changed_when: false

- name: "Health Check"
  uri:
    url: "http://0.0.0.0:3030/api/status"
    method: GET
    status_code: 200
  register: health_check
  until: health_check.status == 200
  retries: 10
  delay: 10

- name: "Display output"
  debug:
    # msg: "{{ server_setup.stdout }}"
    var: server_setup.stdout_lines